#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jun  8 10:08:56 2019

@author: danielqiao
"""

import matplotlib.pyplot as plt
from matplotlib import cm
import pandas as pd
import numpy as np

GDP = pd.read_excel('GDP.xlsx')
GDP = GDP.drop(index=0)
GDP = GDP[::-1]

topuni = pd.read_excel('topuni.xlsx')
topuni = topuni.drop(index=0)
topuni = topuni[::-1]

gdpstr = GDP['GDP'].tolist()
gdp = [float(x) for x in gdpstr]
uni = topuni['Number of Top 100 Universities'].tolist()
diff = [i-100000*j for i in gdp for j in uni]
color = ['White' if x==0 else cm.Reds(abs(x)) for x in diff]
    
fig, ax1 = plt.subplots(figsize=(12,12))

ax1.plot(GDP['Provinces'],GDP['GDP'],'-o')
ax1.set_xlabel('Provinces',rotation=270)
'''
linegraph = plt.plot(GDP['Provinces'],GDP['GDP'],'-o')
bargraph = plt.bar(topuni['Provinces'],height = topuni['Number of Top 100 Universities'])
plt.twinx()

ax1.set_xticklabels(GDP['Provinces'], rotation=270)
#plt.xticks(rotation=270)
#plt.ticklabel_format(style='plain', axis='y')#avoid scientific format
'''



plt.show()